#!/usr/bin/env bash
# Configure Catppuccin for Oh My Zsh and Zellij.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

setup_target_user

OMZ_DIR="${TARGET_HOME}/.oh-my-zsh"
ZSHRC="${TARGET_HOME}/.zshrc"
CATPPUCCIN_ZSH_REPO="https://github.com/JannoTjarks/catppuccin-zsh.git"
ZELLIJ_CONFIG_DIR="${TARGET_HOME}/.config/zellij"
ZELLIJ_CONFIG="${ZELLIJ_CONFIG_DIR}/config.kdl"
zellij_theme="$(zellij_theme_for_flavor)"

# --- Oh My Zsh + Catppuccin ---
if [[ ! -d "${OMZ_DIR}" ]]; then
  die "Oh My Zsh not found at ${OMZ_DIR}. Run 02-zsh-omz.sh first."
fi

themes_dir="${OMZ_DIR}/themes"
flavors_dir="${themes_dir}/catppuccin-flavors"
theme_file="${themes_dir}/catppuccin.zsh-theme"

if [[ -f "${theme_file}" ]]; then
  log "Catppuccin OMZ theme already installed"
else
  log "Installing Catppuccin theme for Oh My Zsh"
  clone_dir="${TARGET_HOME}/.cache/catppuccin-zsh"

  if [[ ! -d "${clone_dir}/.git" ]]; then
    run_as_target_user mkdir -p "$(dirname "${clone_dir}")"
    run_as_target_user git clone --depth 1 "${CATPPUCCIN_ZSH_REPO}" "${clone_dir}"
  fi

  run_as_target_user mkdir -p "${flavors_dir}"
  run_as_target_user ln -sf "${clone_dir}/catppuccin.zsh-theme" "${theme_file}"
  for flavor in "${clone_dir}/catppuccin-flavors/"*; do
    run_as_target_user ln -sf "${flavor}" "${flavors_dir}/$(basename "${flavor}")"
  done
fi

if [[ ! -f "${ZSHRC}" ]]; then
  die ".zshrc not found at ${ZSHRC}. Run 02-zsh-omz.sh first."
fi

log "Configuring Catppuccin in .zshrc (flavor: ${CATPPUCCIN_FLAVOR})"
run_as_target_user cp "${ZSHRC}" "${ZSHRC}.bak-catppuccin"

# Replace or insert ZSH_THEME
if grep -qE '^[[:space:]]*ZSH_THEME=' "${ZSHRC}"; then
  run_as_target_user sed -i "s/^[[:space:]]*ZSH_THEME=.*/ZSH_THEME=\"catppuccin\"/" "${ZSHRC}"
else
  run_as_target_user sed -i "1i ZSH_THEME=\"catppuccin\"" "${ZSHRC}"
fi

catppuccin_marker="# added by comet setup: catppuccin"
if ! grep -qF "${catppuccin_marker}" "${ZSHRC}"; then
  run_as_target_user tee -a "${ZSHRC}" >/dev/null <<EOF

${catppuccin_marker}
CATPPUCCIN_FLAVOR="${CATPPUCCIN_FLAVOR}"
CATPPUCCIN_SHOW_TIME=true
CATPPUCCIN_SHOW_HOSTNAME="ssh"
EOF
else
  run_as_target_user sed -i "s/^CATPPUCCIN_FLAVOR=.*/CATPPUCCIN_FLAVOR=\"${CATPPUCCIN_FLAVOR}\"/" "${ZSHRC}"
fi

# --- Zellij Catppuccin (built-in theme) ---
log "Configuring Zellij theme: ${zellij_theme}"

run_as_target_user mkdir -p "${ZELLIJ_CONFIG_DIR}"

if [[ -f "${ZELLIJ_CONFIG}" ]]; then
  if grep -qE '^[[:space:]]*theme ' "${ZELLIJ_CONFIG}"; then
    run_as_target_user sed -i "s/^[[:space:]]*theme .*/theme \"${zellij_theme}\"/" "${ZELLIJ_CONFIG}"
  else
    run_as_target_user sed -i "1i theme \"${zellij_theme}\"" "${ZELLIJ_CONFIG}"
  fi
else
  run_as_target_user tee "${ZELLIJ_CONFIG}" >/dev/null <<EOF
// Generated by comet setup scripts
theme "${zellij_theme}"

default_shell "zsh"
EOF
fi

log "Catppuccin themes configured (OMZ: ${CATPPUCCIN_FLAVOR}, Zellij: ${zellij_theme})"
